title: Adobe Connect Client
email: brunogasparetto@gmail.com
description: PHP Library to use Adobe Connect API v9.5.4.
baseurl: "/AdobeConnectClient"
url: "https://brunogasparetto.github.io"

repository: brunogasparetto/AdobeConnectClient
markdown: kramdown
theme: jekyll-theme-cayman
